<li <?php if ($this->is_last): ?>class="last"<?php endif; ?>>
    <a href="<?php echo $this->getUrl('gomage_social/'.$this->service.'/login', array('_secure' => true, 'gs_url' => Mage::helper('core')->urlEncode(Mage::helper('core/url')->getCurrentUrl())));  ?>" title="<?php echo $this->getText($this->service) ?>">
        <?php if (($image = $this->getImage($this->service)) && ($this->getLoginType($this->service) == GoMage_Social_Model_Adminhtml_System_Config_Source_Login_Type::IMAGE)): ?>
            <img src="<?php echo $image ?>" alt="<?php echo $this->getText($this->service) ?>" />
        <?php else: ?>
            <?php echo $this->getText($this->service) ?>
        <?php endif; ?>
    </a>
</li>